# Generated by Django 3.2.6 on 2021-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_topheaderwithfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheaderwithfooter',
            name='linkedIn_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='Time_end',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='Time_start',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='developed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='google_plus_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='workingday_end',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topheaderwithfooter',
            name='workingday_start',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
