# Generated by Django 3.2.6 on 2021-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211025_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedIn_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
