# Generated by Django 3.2.6 on 2021-11-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_team_linkedin_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_section_title', models.CharField(max_length=100)),
                ('Team_section_title_extra', models.CharField(max_length=100)),
                ('Team_section_description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
