# Generated by Django 3.2.6 on 2021-10-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
