# Generated by Django 3.2.6 on 2021-11-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_car_section_title', models.CharField(max_length=100)),
                ('featured_car_section_title_extra', models.CharField(max_length=100)),
                ('featured_car_section_description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestCarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latest_car_section_title', models.CharField(max_length=100)),
                ('Latest_car_section_title_extra', models.CharField(max_length=100)),
                ('Latest_car_section_description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
