# Generated by Django 3.2.6 on 2021-11-02 13:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_title_extra', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('about_section_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('about_section_image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('about_section_image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=50)),
                ('service_title', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('service_number', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_section_title', models.CharField(max_length=100)),
                ('service_section_title_extra', models.CharField(max_length=100)),
                ('service_section_description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
